DELETE FROM grupybakterii;
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'VRE                         ','VRE',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'MBL                         ','MBL',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'KPC                         ','KPC',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'AMPC                        ','AMPC',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'ESA                         ','ESA',0,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'WAMPE                       ','AMPE',0,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'EMP                         ','EMP',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'MOP                         ','MOP- nazwa',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'ESBL                        ','ESBL',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'HLAR                        ','HLAR',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'MRSA                        ','MRSA',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'AOPIS                       ','AOPIS',0,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'MRS                         ','MRS',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'STAG                        ','STAG',0,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'BLNAR                       ','BLNAR',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'MLSB                        ','MLSB',1,'');
insert into grupybakterii (id, symbol, nazwa, mechanizmopornosciowy, opis) values (GEN_ID(GenSlowniki, 1),'PENAZ                       ','Penicylinaza',1,'');
