DELETE FROM uzywanebakterie;
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCL','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCTBA','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCU','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCTCAL','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCLSEM','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCTBA','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCT','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCT','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCU','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUSCH','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABI','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABI-','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABI','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABI-','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCLLIG','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCL','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHRXYX','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHRXY','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHR','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHRXYX','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHRXY','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHR','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHRXY','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACHRXYX','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCLSUI','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCL','Nowy');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AA','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AACB','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AAC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AA','Nowy wpis');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AEC','Dodatkowy opis');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','dfsdfdsfdsfsd');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ABCUD','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ACC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ARCA','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ARCA','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ARCA','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ATO','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'ALC','TEST opisow wielo liniowych nana
nowa line');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AFI','Nowy opis');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AAC','');
insert into uzywanebakterie (id,bakteria,opis) values (GEN_ID(GenSlowniki, 1),'AACB','Opis');
